/*
Wazuh API REST

Testing CiscatAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	openapiclient "github.com/EpykLab/wasabi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_api_CiscatAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CiscatAPIService ApiControllersCiscatControllerGetAgentsCiscatResults", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var agentId string

		resp, httpRes, err := apiClient.CiscatAPI.ApiControllersCiscatControllerGetAgentsCiscatResults(context.Background(), agentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
