/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the OverviewAgentsAgentOsInnerOs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverviewAgentsAgentOsInnerOs{}

// OverviewAgentsAgentOsInnerOs struct for OverviewAgentsAgentOsInnerOs
type OverviewAgentsAgentOsInnerOs struct {
	Name *string `json:"name,omitempty"`
	Platform *string `json:"platform,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewOverviewAgentsAgentOsInnerOs instantiates a new OverviewAgentsAgentOsInnerOs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverviewAgentsAgentOsInnerOs() *OverviewAgentsAgentOsInnerOs {
	this := OverviewAgentsAgentOsInnerOs{}
	return &this
}

// NewOverviewAgentsAgentOsInnerOsWithDefaults instantiates a new OverviewAgentsAgentOsInnerOs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverviewAgentsAgentOsInnerOsWithDefaults() *OverviewAgentsAgentOsInnerOs {
	this := OverviewAgentsAgentOsInnerOs{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OverviewAgentsAgentOsInnerOs) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverviewAgentsAgentOsInnerOs) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OverviewAgentsAgentOsInnerOs) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OverviewAgentsAgentOsInnerOs) SetName(v string) {
	o.Name = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *OverviewAgentsAgentOsInnerOs) GetPlatform() string {
	if o == nil || IsNil(o.Platform) {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverviewAgentsAgentOsInnerOs) GetPlatformOk() (*string, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *OverviewAgentsAgentOsInnerOs) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *OverviewAgentsAgentOsInnerOs) SetPlatform(v string) {
	o.Platform = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *OverviewAgentsAgentOsInnerOs) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverviewAgentsAgentOsInnerOs) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *OverviewAgentsAgentOsInnerOs) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *OverviewAgentsAgentOsInnerOs) SetVersion(v string) {
	o.Version = &v
}

func (o OverviewAgentsAgentOsInnerOs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverviewAgentsAgentOsInnerOs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableOverviewAgentsAgentOsInnerOs struct {
	value *OverviewAgentsAgentOsInnerOs
	isSet bool
}

func (v NullableOverviewAgentsAgentOsInnerOs) Get() *OverviewAgentsAgentOsInnerOs {
	return v.value
}

func (v *NullableOverviewAgentsAgentOsInnerOs) Set(val *OverviewAgentsAgentOsInnerOs) {
	v.value = val
	v.isSet = true
}

func (v NullableOverviewAgentsAgentOsInnerOs) IsSet() bool {
	return v.isSet
}

func (v *NullableOverviewAgentsAgentOsInnerOs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverviewAgentsAgentOsInnerOs(val *OverviewAgentsAgentOsInnerOs) *NullableOverviewAgentsAgentOsInnerOs {
	return &NullableOverviewAgentsAgentOsInnerOs{value: val, isSet: true}
}

func (v NullableOverviewAgentsAgentOsInnerOs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverviewAgentsAgentOsInnerOs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


