/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AgentsSummaryStatusConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentsSummaryStatusConfiguration{}

// AgentsSummaryStatusConfiguration struct for AgentsSummaryStatusConfiguration
type AgentsSummaryStatusConfiguration struct {
	Total *int32 `json:"total,omitempty"`
	Synced *int32 `json:"synced,omitempty"`
	NotSynced *int32 `json:"not_synced,omitempty"`
}

// NewAgentsSummaryStatusConfiguration instantiates a new AgentsSummaryStatusConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSummaryStatusConfiguration() *AgentsSummaryStatusConfiguration {
	this := AgentsSummaryStatusConfiguration{}
	return &this
}

// NewAgentsSummaryStatusConfigurationWithDefaults instantiates a new AgentsSummaryStatusConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSummaryStatusConfigurationWithDefaults() *AgentsSummaryStatusConfiguration {
	this := AgentsSummaryStatusConfiguration{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AgentsSummaryStatusConfiguration) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSummaryStatusConfiguration) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AgentsSummaryStatusConfiguration) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AgentsSummaryStatusConfiguration) SetTotal(v int32) {
	o.Total = &v
}

// GetSynced returns the Synced field value if set, zero value otherwise.
func (o *AgentsSummaryStatusConfiguration) GetSynced() int32 {
	if o == nil || IsNil(o.Synced) {
		var ret int32
		return ret
	}
	return *o.Synced
}

// GetSyncedOk returns a tuple with the Synced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSummaryStatusConfiguration) GetSyncedOk() (*int32, bool) {
	if o == nil || IsNil(o.Synced) {
		return nil, false
	}
	return o.Synced, true
}

// HasSynced returns a boolean if a field has been set.
func (o *AgentsSummaryStatusConfiguration) HasSynced() bool {
	if o != nil && !IsNil(o.Synced) {
		return true
	}

	return false
}

// SetSynced gets a reference to the given int32 and assigns it to the Synced field.
func (o *AgentsSummaryStatusConfiguration) SetSynced(v int32) {
	o.Synced = &v
}

// GetNotSynced returns the NotSynced field value if set, zero value otherwise.
func (o *AgentsSummaryStatusConfiguration) GetNotSynced() int32 {
	if o == nil || IsNil(o.NotSynced) {
		var ret int32
		return ret
	}
	return *o.NotSynced
}

// GetNotSyncedOk returns a tuple with the NotSynced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSummaryStatusConfiguration) GetNotSyncedOk() (*int32, bool) {
	if o == nil || IsNil(o.NotSynced) {
		return nil, false
	}
	return o.NotSynced, true
}

// HasNotSynced returns a boolean if a field has been set.
func (o *AgentsSummaryStatusConfiguration) HasNotSynced() bool {
	if o != nil && !IsNil(o.NotSynced) {
		return true
	}

	return false
}

// SetNotSynced gets a reference to the given int32 and assigns it to the NotSynced field.
func (o *AgentsSummaryStatusConfiguration) SetNotSynced(v int32) {
	o.NotSynced = &v
}

func (o AgentsSummaryStatusConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentsSummaryStatusConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Synced) {
		toSerialize["synced"] = o.Synced
	}
	if !IsNil(o.NotSynced) {
		toSerialize["not_synced"] = o.NotSynced
	}
	return toSerialize, nil
}

type NullableAgentsSummaryStatusConfiguration struct {
	value *AgentsSummaryStatusConfiguration
	isSet bool
}

func (v NullableAgentsSummaryStatusConfiguration) Get() *AgentsSummaryStatusConfiguration {
	return v.value
}

func (v *NullableAgentsSummaryStatusConfiguration) Set(val *AgentsSummaryStatusConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSummaryStatusConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSummaryStatusConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSummaryStatusConfiguration(val *AgentsSummaryStatusConfiguration) *NullableAgentsSummaryStatusConfiguration {
	return &NullableAgentsSummaryStatusConfiguration{value: val, isSet: true}
}

func (v NullableAgentsSummaryStatusConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSummaryStatusConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


