/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SecurityConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityConfiguration{}

// SecurityConfiguration struct for SecurityConfiguration
type SecurityConfiguration struct {
	// Time in seconds until the token expires
	AuthTokenExpTimeout *int32 `json:"auth_token_exp_timeout,omitempty"`
	// RBAC mode (white/black)
	RbacMode *string `json:"rbac_mode,omitempty"`
}

// NewSecurityConfiguration instantiates a new SecurityConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityConfiguration() *SecurityConfiguration {
	this := SecurityConfiguration{}
	return &this
}

// NewSecurityConfigurationWithDefaults instantiates a new SecurityConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecurityConfigurationWithDefaults() *SecurityConfiguration {
	this := SecurityConfiguration{}
	return &this
}

// GetAuthTokenExpTimeout returns the AuthTokenExpTimeout field value if set, zero value otherwise.
func (o *SecurityConfiguration) GetAuthTokenExpTimeout() int32 {
	if o == nil || IsNil(o.AuthTokenExpTimeout) {
		var ret int32
		return ret
	}
	return *o.AuthTokenExpTimeout
}

// GetAuthTokenExpTimeoutOk returns a tuple with the AuthTokenExpTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityConfiguration) GetAuthTokenExpTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.AuthTokenExpTimeout) {
		return nil, false
	}
	return o.AuthTokenExpTimeout, true
}

// HasAuthTokenExpTimeout returns a boolean if a field has been set.
func (o *SecurityConfiguration) HasAuthTokenExpTimeout() bool {
	if o != nil && !IsNil(o.AuthTokenExpTimeout) {
		return true
	}

	return false
}

// SetAuthTokenExpTimeout gets a reference to the given int32 and assigns it to the AuthTokenExpTimeout field.
func (o *SecurityConfiguration) SetAuthTokenExpTimeout(v int32) {
	o.AuthTokenExpTimeout = &v
}

// GetRbacMode returns the RbacMode field value if set, zero value otherwise.
func (o *SecurityConfiguration) GetRbacMode() string {
	if o == nil || IsNil(o.RbacMode) {
		var ret string
		return ret
	}
	return *o.RbacMode
}

// GetRbacModeOk returns a tuple with the RbacMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityConfiguration) GetRbacModeOk() (*string, bool) {
	if o == nil || IsNil(o.RbacMode) {
		return nil, false
	}
	return o.RbacMode, true
}

// HasRbacMode returns a boolean if a field has been set.
func (o *SecurityConfiguration) HasRbacMode() bool {
	if o != nil && !IsNil(o.RbacMode) {
		return true
	}

	return false
}

// SetRbacMode gets a reference to the given string and assigns it to the RbacMode field.
func (o *SecurityConfiguration) SetRbacMode(v string) {
	o.RbacMode = &v
}

func (o SecurityConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthTokenExpTimeout) {
		toSerialize["auth_token_exp_timeout"] = o.AuthTokenExpTimeout
	}
	if !IsNil(o.RbacMode) {
		toSerialize["rbac_mode"] = o.RbacMode
	}
	return toSerialize, nil
}

type NullableSecurityConfiguration struct {
	value *SecurityConfiguration
	isSet bool
}

func (v NullableSecurityConfiguration) Get() *SecurityConfiguration {
	return v.value
}

func (v *NullableSecurityConfiguration) Set(val *SecurityConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityConfiguration(val *SecurityConfiguration) *NullableSecurityConfiguration {
	return &NullableSecurityConfiguration{value: val, isSet: true}
}

func (v NullableSecurityConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


