/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SyscollectorHardwareCpu type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyscollectorHardwareCpu{}

// SyscollectorHardwareCpu struct for SyscollectorHardwareCpu
type SyscollectorHardwareCpu struct {
	// Number of cores the CPU has
	Cores *int32 `json:"cores,omitempty"`
	// Mhz the CPU has
	Mhz *float32 `json:"mhz,omitempty"`
	// CPU name
	Name *string `json:"name,omitempty"`
}

// NewSyscollectorHardwareCpu instantiates a new SyscollectorHardwareCpu object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyscollectorHardwareCpu() *SyscollectorHardwareCpu {
	this := SyscollectorHardwareCpu{}
	return &this
}

// NewSyscollectorHardwareCpuWithDefaults instantiates a new SyscollectorHardwareCpu object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyscollectorHardwareCpuWithDefaults() *SyscollectorHardwareCpu {
	this := SyscollectorHardwareCpu{}
	return &this
}

// GetCores returns the Cores field value if set, zero value otherwise.
func (o *SyscollectorHardwareCpu) GetCores() int32 {
	if o == nil || IsNil(o.Cores) {
		var ret int32
		return ret
	}
	return *o.Cores
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyscollectorHardwareCpu) GetCoresOk() (*int32, bool) {
	if o == nil || IsNil(o.Cores) {
		return nil, false
	}
	return o.Cores, true
}

// HasCores returns a boolean if a field has been set.
func (o *SyscollectorHardwareCpu) HasCores() bool {
	if o != nil && !IsNil(o.Cores) {
		return true
	}

	return false
}

// SetCores gets a reference to the given int32 and assigns it to the Cores field.
func (o *SyscollectorHardwareCpu) SetCores(v int32) {
	o.Cores = &v
}

// GetMhz returns the Mhz field value if set, zero value otherwise.
func (o *SyscollectorHardwareCpu) GetMhz() float32 {
	if o == nil || IsNil(o.Mhz) {
		var ret float32
		return ret
	}
	return *o.Mhz
}

// GetMhzOk returns a tuple with the Mhz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyscollectorHardwareCpu) GetMhzOk() (*float32, bool) {
	if o == nil || IsNil(o.Mhz) {
		return nil, false
	}
	return o.Mhz, true
}

// HasMhz returns a boolean if a field has been set.
func (o *SyscollectorHardwareCpu) HasMhz() bool {
	if o != nil && !IsNil(o.Mhz) {
		return true
	}

	return false
}

// SetMhz gets a reference to the given float32 and assigns it to the Mhz field.
func (o *SyscollectorHardwareCpu) SetMhz(v float32) {
	o.Mhz = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SyscollectorHardwareCpu) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyscollectorHardwareCpu) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SyscollectorHardwareCpu) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SyscollectorHardwareCpu) SetName(v string) {
	o.Name = &v
}

func (o SyscollectorHardwareCpu) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyscollectorHardwareCpu) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cores) {
		toSerialize["cores"] = o.Cores
	}
	if !IsNil(o.Mhz) {
		toSerialize["mhz"] = o.Mhz
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSyscollectorHardwareCpu struct {
	value *SyscollectorHardwareCpu
	isSet bool
}

func (v NullableSyscollectorHardwareCpu) Get() *SyscollectorHardwareCpu {
	return v.value
}

func (v *NullableSyscollectorHardwareCpu) Set(val *SyscollectorHardwareCpu) {
	v.value = val
	v.isSet = true
}

func (v NullableSyscollectorHardwareCpu) IsSet() bool {
	return v.isSet
}

func (v *NullableSyscollectorHardwareCpu) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyscollectorHardwareCpu(val *SyscollectorHardwareCpu) *NullableSyscollectorHardwareCpu {
	return &NullableSyscollectorHardwareCpu{value: val, isSet: true}
}

func (v NullableSyscollectorHardwareCpu) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyscollectorHardwareCpu) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


