/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// SimpleApiErrorIdInner - struct for SimpleApiErrorIdInner
type SimpleApiErrorIdInner struct {
	Int32 *int32
	String *string
}

// int32AsSimpleApiErrorIdInner is a convenience function that returns int32 wrapped in SimpleApiErrorIdInner
func Int32AsSimpleApiErrorIdInner(v *int32) SimpleApiErrorIdInner {
	return SimpleApiErrorIdInner{
		Int32: v,
	}
}

// stringAsSimpleApiErrorIdInner is a convenience function that returns string wrapped in SimpleApiErrorIdInner
func StringAsSimpleApiErrorIdInner(v *string) SimpleApiErrorIdInner {
	return SimpleApiErrorIdInner{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SimpleApiErrorIdInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SimpleApiErrorIdInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SimpleApiErrorIdInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SimpleApiErrorIdInner) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SimpleApiErrorIdInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SimpleApiErrorIdInner) GetActualInstanceValue() (interface{}) {
	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableSimpleApiErrorIdInner struct {
	value *SimpleApiErrorIdInner
	isSet bool
}

func (v NullableSimpleApiErrorIdInner) Get() *SimpleApiErrorIdInner {
	return v.value
}

func (v *NullableSimpleApiErrorIdInner) Set(val *SimpleApiErrorIdInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSimpleApiErrorIdInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSimpleApiErrorIdInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimpleApiErrorIdInner(val *SimpleApiErrorIdInner) *NullableSimpleApiErrorIdInner {
	return &NullableSimpleApiErrorIdInner{value: val, isSet: true}
}

func (v NullableSimpleApiErrorIdInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimpleApiErrorIdInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


