/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown{}

// WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown struct for WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown
type WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown struct {
	Db *WazuhDBStatsItemMetricsQueriesReceivedBreakdownMitreBreakdownDb `json:"db,omitempty"`
	Tables *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownTables `json:"tables,omitempty"`
}

// NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown instantiates a new WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown() *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown {
	this := WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown{}
	return &this
}

// NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownWithDefaults instantiates a new WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownWithDefaults() *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown {
	this := WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown{}
	return &this
}

// GetDb returns the Db field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) GetDb() WazuhDBStatsItemMetricsQueriesReceivedBreakdownMitreBreakdownDb {
	if o == nil || IsNil(o.Db) {
		var ret WazuhDBStatsItemMetricsQueriesReceivedBreakdownMitreBreakdownDb
		return ret
	}
	return *o.Db
}

// GetDbOk returns a tuple with the Db field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) GetDbOk() (*WazuhDBStatsItemMetricsQueriesReceivedBreakdownMitreBreakdownDb, bool) {
	if o == nil || IsNil(o.Db) {
		return nil, false
	}
	return o.Db, true
}

// HasDb returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) HasDb() bool {
	if o != nil && !IsNil(o.Db) {
		return true
	}

	return false
}

// SetDb gets a reference to the given WazuhDBStatsItemMetricsQueriesReceivedBreakdownMitreBreakdownDb and assigns it to the Db field.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) SetDb(v WazuhDBStatsItemMetricsQueriesReceivedBreakdownMitreBreakdownDb) {
	o.Db = &v
}

// GetTables returns the Tables field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) GetTables() WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownTables {
	if o == nil || IsNil(o.Tables) {
		var ret WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownTables
		return ret
	}
	return *o.Tables
}

// GetTablesOk returns a tuple with the Tables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) GetTablesOk() (*WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownTables, bool) {
	if o == nil || IsNil(o.Tables) {
		return nil, false
	}
	return o.Tables, true
}

// HasTables returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) HasTables() bool {
	if o != nil && !IsNil(o.Tables) {
		return true
	}

	return false
}

// SetTables gets a reference to the given WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownTables and assigns it to the Tables field.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) SetTables(v WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdownTables) {
	o.Tables = &v
}

func (o WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Db) {
		toSerialize["db"] = o.Db
	}
	if !IsNil(o.Tables) {
		toSerialize["tables"] = o.Tables
	}
	return toSerialize, nil
}

type NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown struct {
	value *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown
	isSet bool
}

func (v NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) Get() *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown {
	return v.value
}

func (v *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) Set(val *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown(val *WazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown {
	return &NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown{value: val, isSet: true}
}

func (v NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownTaskBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


