/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup{}

// WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup struct for WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup
type WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup struct {
	DeleteGroup *int32 `json:"delete-group,omitempty"`
	FindGroup *int32 `json:"find-group,omitempty"`
	InsertAgentGroup *int32 `json:"insert-agent-group,omitempty"`
	SelectGroups *int32 `json:"select-groups,omitempty"`
}

// NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup instantiates a new WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup() *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup {
	this := WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup{}
	return &this
}

// NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroupWithDefaults instantiates a new WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroupWithDefaults() *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup {
	this := WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup{}
	return &this
}

// GetDeleteGroup returns the DeleteGroup field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetDeleteGroup() int32 {
	if o == nil || IsNil(o.DeleteGroup) {
		var ret int32
		return ret
	}
	return *o.DeleteGroup
}

// GetDeleteGroupOk returns a tuple with the DeleteGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetDeleteGroupOk() (*int32, bool) {
	if o == nil || IsNil(o.DeleteGroup) {
		return nil, false
	}
	return o.DeleteGroup, true
}

// HasDeleteGroup returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) HasDeleteGroup() bool {
	if o != nil && !IsNil(o.DeleteGroup) {
		return true
	}

	return false
}

// SetDeleteGroup gets a reference to the given int32 and assigns it to the DeleteGroup field.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) SetDeleteGroup(v int32) {
	o.DeleteGroup = &v
}

// GetFindGroup returns the FindGroup field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetFindGroup() int32 {
	if o == nil || IsNil(o.FindGroup) {
		var ret int32
		return ret
	}
	return *o.FindGroup
}

// GetFindGroupOk returns a tuple with the FindGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetFindGroupOk() (*int32, bool) {
	if o == nil || IsNil(o.FindGroup) {
		return nil, false
	}
	return o.FindGroup, true
}

// HasFindGroup returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) HasFindGroup() bool {
	if o != nil && !IsNil(o.FindGroup) {
		return true
	}

	return false
}

// SetFindGroup gets a reference to the given int32 and assigns it to the FindGroup field.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) SetFindGroup(v int32) {
	o.FindGroup = &v
}

// GetInsertAgentGroup returns the InsertAgentGroup field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetInsertAgentGroup() int32 {
	if o == nil || IsNil(o.InsertAgentGroup) {
		var ret int32
		return ret
	}
	return *o.InsertAgentGroup
}

// GetInsertAgentGroupOk returns a tuple with the InsertAgentGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetInsertAgentGroupOk() (*int32, bool) {
	if o == nil || IsNil(o.InsertAgentGroup) {
		return nil, false
	}
	return o.InsertAgentGroup, true
}

// HasInsertAgentGroup returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) HasInsertAgentGroup() bool {
	if o != nil && !IsNil(o.InsertAgentGroup) {
		return true
	}

	return false
}

// SetInsertAgentGroup gets a reference to the given int32 and assigns it to the InsertAgentGroup field.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) SetInsertAgentGroup(v int32) {
	o.InsertAgentGroup = &v
}

// GetSelectGroups returns the SelectGroups field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetSelectGroups() int32 {
	if o == nil || IsNil(o.SelectGroups) {
		var ret int32
		return ret
	}
	return *o.SelectGroups
}

// GetSelectGroupsOk returns a tuple with the SelectGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) GetSelectGroupsOk() (*int32, bool) {
	if o == nil || IsNil(o.SelectGroups) {
		return nil, false
	}
	return o.SelectGroups, true
}

// HasSelectGroups returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) HasSelectGroups() bool {
	if o != nil && !IsNil(o.SelectGroups) {
		return true
	}

	return false
}

// SetSelectGroups gets a reference to the given int32 and assigns it to the SelectGroups field.
func (o *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) SetSelectGroups(v int32) {
	o.SelectGroups = &v
}

func (o WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeleteGroup) {
		toSerialize["delete-group"] = o.DeleteGroup
	}
	if !IsNil(o.FindGroup) {
		toSerialize["find-group"] = o.FindGroup
	}
	if !IsNil(o.InsertAgentGroup) {
		toSerialize["insert-agent-group"] = o.InsertAgentGroup
	}
	if !IsNil(o.SelectGroups) {
		toSerialize["select-groups"] = o.SelectGroups
	}
	return toSerialize, nil
}

type NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup struct {
	value *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup
	isSet bool
}

func (v NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) Get() *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup {
	return v.value
}

func (v *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) Set(val *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup(val *WazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup {
	return &NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup{value: val, isSet: true}
}

func (v NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWazuhDBStatsItemMetricsQueriesReceivedBreakdownGlobalBreakdownTablesGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


