/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WazuhDBStatsItemMetricsTimeExecutionBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WazuhDBStatsItemMetricsTimeExecutionBreakdown{}

// WazuhDBStatsItemMetricsTimeExecutionBreakdown struct for WazuhDBStatsItemMetricsTimeExecutionBreakdown
type WazuhDBStatsItemMetricsTimeExecutionBreakdown struct {
	// Time taken by all agent queries (milliseconds)
	Agent *int32 `json:"agent,omitempty"`
	AgentBreakdown *WazuhDBStatsItemMetricsTimeExecutionBreakdownAgentBreakdown `json:"agent_breakdown,omitempty"`
	// Time taken by all global queries (milliseconds)
	Global *int32 `json:"global,omitempty"`
	GlobalBreakdown *WazuhDBStatsItemMetricsTimeExecutionBreakdownGlobalBreakdown `json:"global_breakdown,omitempty"`
	// Time taken by all mitre queries (milliseconds)
	Mitre *int32 `json:"mitre,omitempty"`
	MitreBreakdown *WazuhDBStatsItemMetricsTimeExecutionBreakdownMitreBreakdown `json:"mitre_breakdown,omitempty"`
	// Time taken by all task queries (milliseconds)
	Task *int32 `json:"task,omitempty"`
	TaskBreakdown *WazuhDBStatsItemMetricsTimeExecutionBreakdownTaskBreakdown `json:"task_breakdown,omitempty"`
	// Time taken by all wazuhdb queries (milliseconds)
	Wazuhdb *int32 `json:"wazuhdb,omitempty"`
	WazuhdbBreakdown *WazuhDBStatsItemMetricsTimeExecutionBreakdownWazuhdbBreakdown `json:"wazuhdb_breakdown,omitempty"`
}

// NewWazuhDBStatsItemMetricsTimeExecutionBreakdown instantiates a new WazuhDBStatsItemMetricsTimeExecutionBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWazuhDBStatsItemMetricsTimeExecutionBreakdown() *WazuhDBStatsItemMetricsTimeExecutionBreakdown {
	this := WazuhDBStatsItemMetricsTimeExecutionBreakdown{}
	return &this
}

// NewWazuhDBStatsItemMetricsTimeExecutionBreakdownWithDefaults instantiates a new WazuhDBStatsItemMetricsTimeExecutionBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWazuhDBStatsItemMetricsTimeExecutionBreakdownWithDefaults() *WazuhDBStatsItemMetricsTimeExecutionBreakdown {
	this := WazuhDBStatsItemMetricsTimeExecutionBreakdown{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetAgent() int32 {
	if o == nil || IsNil(o.Agent) {
		var ret int32
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetAgentOk() (*int32, bool) {
	if o == nil || IsNil(o.Agent) {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given int32 and assigns it to the Agent field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetAgent(v int32) {
	o.Agent = &v
}

// GetAgentBreakdown returns the AgentBreakdown field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetAgentBreakdown() WazuhDBStatsItemMetricsTimeExecutionBreakdownAgentBreakdown {
	if o == nil || IsNil(o.AgentBreakdown) {
		var ret WazuhDBStatsItemMetricsTimeExecutionBreakdownAgentBreakdown
		return ret
	}
	return *o.AgentBreakdown
}

// GetAgentBreakdownOk returns a tuple with the AgentBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetAgentBreakdownOk() (*WazuhDBStatsItemMetricsTimeExecutionBreakdownAgentBreakdown, bool) {
	if o == nil || IsNil(o.AgentBreakdown) {
		return nil, false
	}
	return o.AgentBreakdown, true
}

// HasAgentBreakdown returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasAgentBreakdown() bool {
	if o != nil && !IsNil(o.AgentBreakdown) {
		return true
	}

	return false
}

// SetAgentBreakdown gets a reference to the given WazuhDBStatsItemMetricsTimeExecutionBreakdownAgentBreakdown and assigns it to the AgentBreakdown field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetAgentBreakdown(v WazuhDBStatsItemMetricsTimeExecutionBreakdownAgentBreakdown) {
	o.AgentBreakdown = &v
}

// GetGlobal returns the Global field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetGlobal() int32 {
	if o == nil || IsNil(o.Global) {
		var ret int32
		return ret
	}
	return *o.Global
}

// GetGlobalOk returns a tuple with the Global field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetGlobalOk() (*int32, bool) {
	if o == nil || IsNil(o.Global) {
		return nil, false
	}
	return o.Global, true
}

// HasGlobal returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasGlobal() bool {
	if o != nil && !IsNil(o.Global) {
		return true
	}

	return false
}

// SetGlobal gets a reference to the given int32 and assigns it to the Global field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetGlobal(v int32) {
	o.Global = &v
}

// GetGlobalBreakdown returns the GlobalBreakdown field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetGlobalBreakdown() WazuhDBStatsItemMetricsTimeExecutionBreakdownGlobalBreakdown {
	if o == nil || IsNil(o.GlobalBreakdown) {
		var ret WazuhDBStatsItemMetricsTimeExecutionBreakdownGlobalBreakdown
		return ret
	}
	return *o.GlobalBreakdown
}

// GetGlobalBreakdownOk returns a tuple with the GlobalBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetGlobalBreakdownOk() (*WazuhDBStatsItemMetricsTimeExecutionBreakdownGlobalBreakdown, bool) {
	if o == nil || IsNil(o.GlobalBreakdown) {
		return nil, false
	}
	return o.GlobalBreakdown, true
}

// HasGlobalBreakdown returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasGlobalBreakdown() bool {
	if o != nil && !IsNil(o.GlobalBreakdown) {
		return true
	}

	return false
}

// SetGlobalBreakdown gets a reference to the given WazuhDBStatsItemMetricsTimeExecutionBreakdownGlobalBreakdown and assigns it to the GlobalBreakdown field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetGlobalBreakdown(v WazuhDBStatsItemMetricsTimeExecutionBreakdownGlobalBreakdown) {
	o.GlobalBreakdown = &v
}

// GetMitre returns the Mitre field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetMitre() int32 {
	if o == nil || IsNil(o.Mitre) {
		var ret int32
		return ret
	}
	return *o.Mitre
}

// GetMitreOk returns a tuple with the Mitre field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetMitreOk() (*int32, bool) {
	if o == nil || IsNil(o.Mitre) {
		return nil, false
	}
	return o.Mitre, true
}

// HasMitre returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasMitre() bool {
	if o != nil && !IsNil(o.Mitre) {
		return true
	}

	return false
}

// SetMitre gets a reference to the given int32 and assigns it to the Mitre field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetMitre(v int32) {
	o.Mitre = &v
}

// GetMitreBreakdown returns the MitreBreakdown field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetMitreBreakdown() WazuhDBStatsItemMetricsTimeExecutionBreakdownMitreBreakdown {
	if o == nil || IsNil(o.MitreBreakdown) {
		var ret WazuhDBStatsItemMetricsTimeExecutionBreakdownMitreBreakdown
		return ret
	}
	return *o.MitreBreakdown
}

// GetMitreBreakdownOk returns a tuple with the MitreBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetMitreBreakdownOk() (*WazuhDBStatsItemMetricsTimeExecutionBreakdownMitreBreakdown, bool) {
	if o == nil || IsNil(o.MitreBreakdown) {
		return nil, false
	}
	return o.MitreBreakdown, true
}

// HasMitreBreakdown returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasMitreBreakdown() bool {
	if o != nil && !IsNil(o.MitreBreakdown) {
		return true
	}

	return false
}

// SetMitreBreakdown gets a reference to the given WazuhDBStatsItemMetricsTimeExecutionBreakdownMitreBreakdown and assigns it to the MitreBreakdown field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetMitreBreakdown(v WazuhDBStatsItemMetricsTimeExecutionBreakdownMitreBreakdown) {
	o.MitreBreakdown = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetTask() int32 {
	if o == nil || IsNil(o.Task) {
		var ret int32
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetTaskOk() (*int32, bool) {
	if o == nil || IsNil(o.Task) {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasTask() bool {
	if o != nil && !IsNil(o.Task) {
		return true
	}

	return false
}

// SetTask gets a reference to the given int32 and assigns it to the Task field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetTask(v int32) {
	o.Task = &v
}

// GetTaskBreakdown returns the TaskBreakdown field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetTaskBreakdown() WazuhDBStatsItemMetricsTimeExecutionBreakdownTaskBreakdown {
	if o == nil || IsNil(o.TaskBreakdown) {
		var ret WazuhDBStatsItemMetricsTimeExecutionBreakdownTaskBreakdown
		return ret
	}
	return *o.TaskBreakdown
}

// GetTaskBreakdownOk returns a tuple with the TaskBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetTaskBreakdownOk() (*WazuhDBStatsItemMetricsTimeExecutionBreakdownTaskBreakdown, bool) {
	if o == nil || IsNil(o.TaskBreakdown) {
		return nil, false
	}
	return o.TaskBreakdown, true
}

// HasTaskBreakdown returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasTaskBreakdown() bool {
	if o != nil && !IsNil(o.TaskBreakdown) {
		return true
	}

	return false
}

// SetTaskBreakdown gets a reference to the given WazuhDBStatsItemMetricsTimeExecutionBreakdownTaskBreakdown and assigns it to the TaskBreakdown field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetTaskBreakdown(v WazuhDBStatsItemMetricsTimeExecutionBreakdownTaskBreakdown) {
	o.TaskBreakdown = &v
}

// GetWazuhdb returns the Wazuhdb field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetWazuhdb() int32 {
	if o == nil || IsNil(o.Wazuhdb) {
		var ret int32
		return ret
	}
	return *o.Wazuhdb
}

// GetWazuhdbOk returns a tuple with the Wazuhdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetWazuhdbOk() (*int32, bool) {
	if o == nil || IsNil(o.Wazuhdb) {
		return nil, false
	}
	return o.Wazuhdb, true
}

// HasWazuhdb returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasWazuhdb() bool {
	if o != nil && !IsNil(o.Wazuhdb) {
		return true
	}

	return false
}

// SetWazuhdb gets a reference to the given int32 and assigns it to the Wazuhdb field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetWazuhdb(v int32) {
	o.Wazuhdb = &v
}

// GetWazuhdbBreakdown returns the WazuhdbBreakdown field value if set, zero value otherwise.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetWazuhdbBreakdown() WazuhDBStatsItemMetricsTimeExecutionBreakdownWazuhdbBreakdown {
	if o == nil || IsNil(o.WazuhdbBreakdown) {
		var ret WazuhDBStatsItemMetricsTimeExecutionBreakdownWazuhdbBreakdown
		return ret
	}
	return *o.WazuhdbBreakdown
}

// GetWazuhdbBreakdownOk returns a tuple with the WazuhdbBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) GetWazuhdbBreakdownOk() (*WazuhDBStatsItemMetricsTimeExecutionBreakdownWazuhdbBreakdown, bool) {
	if o == nil || IsNil(o.WazuhdbBreakdown) {
		return nil, false
	}
	return o.WazuhdbBreakdown, true
}

// HasWazuhdbBreakdown returns a boolean if a field has been set.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) HasWazuhdbBreakdown() bool {
	if o != nil && !IsNil(o.WazuhdbBreakdown) {
		return true
	}

	return false
}

// SetWazuhdbBreakdown gets a reference to the given WazuhDBStatsItemMetricsTimeExecutionBreakdownWazuhdbBreakdown and assigns it to the WazuhdbBreakdown field.
func (o *WazuhDBStatsItemMetricsTimeExecutionBreakdown) SetWazuhdbBreakdown(v WazuhDBStatsItemMetricsTimeExecutionBreakdownWazuhdbBreakdown) {
	o.WazuhdbBreakdown = &v
}

func (o WazuhDBStatsItemMetricsTimeExecutionBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WazuhDBStatsItemMetricsTimeExecutionBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Agent) {
		toSerialize["agent"] = o.Agent
	}
	if !IsNil(o.AgentBreakdown) {
		toSerialize["agent_breakdown"] = o.AgentBreakdown
	}
	if !IsNil(o.Global) {
		toSerialize["global"] = o.Global
	}
	if !IsNil(o.GlobalBreakdown) {
		toSerialize["global_breakdown"] = o.GlobalBreakdown
	}
	if !IsNil(o.Mitre) {
		toSerialize["mitre"] = o.Mitre
	}
	if !IsNil(o.MitreBreakdown) {
		toSerialize["mitre_breakdown"] = o.MitreBreakdown
	}
	if !IsNil(o.Task) {
		toSerialize["task"] = o.Task
	}
	if !IsNil(o.TaskBreakdown) {
		toSerialize["task_breakdown"] = o.TaskBreakdown
	}
	if !IsNil(o.Wazuhdb) {
		toSerialize["wazuhdb"] = o.Wazuhdb
	}
	if !IsNil(o.WazuhdbBreakdown) {
		toSerialize["wazuhdb_breakdown"] = o.WazuhdbBreakdown
	}
	return toSerialize, nil
}

type NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown struct {
	value *WazuhDBStatsItemMetricsTimeExecutionBreakdown
	isSet bool
}

func (v NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown) Get() *WazuhDBStatsItemMetricsTimeExecutionBreakdown {
	return v.value
}

func (v *NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown) Set(val *WazuhDBStatsItemMetricsTimeExecutionBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWazuhDBStatsItemMetricsTimeExecutionBreakdown(val *WazuhDBStatsItemMetricsTimeExecutionBreakdown) *NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown {
	return &NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown{value: val, isSet: true}
}

func (v NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWazuhDBStatsItemMetricsTimeExecutionBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


