/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown{}

// WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown struct for WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown
type WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown struct {
	// Events discarded from AWS module because the queue was full
	Aws *int32 `json:"aws,omitempty"`
	// Events discarded from Azure module because the queue was full
	Azure *int32 `json:"azure,omitempty"`
	// Events discarded from CIS-CAT module because the queue was full
	Ciscat *int32 `json:"ciscat,omitempty"`
	// Events discarded from command module because the queue was full
	Command *int32 `json:"command,omitempty"`
	// Events discarded from Docker module because the queue was full
	Docker *int32 `json:"docker,omitempty"`
	// Events discarded from GCP module because the queue was full
	Gcp *int32 `json:"gcp,omitempty"`
	// Events discarded from GitHub module because the queue was full
	Github *int32 `json:"github,omitempty"`
	LogcollectorBreakdown *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownLogcollectorBreakdown `json:"logcollector_breakdown,omitempty"`
	// Events discarded from Office365 module because the queue was full
	Office365 *int32 `json:"office365,omitempty"`
	// Events discarded from ms-graph module because the queue was full
	MsGraph *int32 `json:"ms-graph,omitempty"`
	// Events discarded from OSCAP module because the queue was full
	Oscap *int32 `json:"oscap,omitempty"`
	// Events discarded from OSQuery module because the queue was full
	Osquery *int32 `json:"osquery,omitempty"`
	// Events discarded from rootcheck (syscheckd) because the queue was full
	Rootcheck *int32 `json:"rootcheck,omitempty"`
	// Events discarded from SCA module because the queue was full
	Sca *int32 `json:"sca,omitempty"`
	// Events discarded from syscheckd because the queue was full
	Syscheck *int32 `json:"syscheck,omitempty"`
	// Events discarded from syscollector module because the queue was full
	Syscollector *int32 `json:"syscollector,omitempty"`
	// Events discarded from upgrade agent module because the queue was full
	Upgrade *int32 `json:"upgrade,omitempty"`
}

// NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown instantiates a new WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown() *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown {
	this := WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown{}
	return &this
}

// NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownWithDefaults instantiates a new WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownWithDefaults() *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown {
	this := WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown{}
	return &this
}

// GetAws returns the Aws field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetAws() int32 {
	if o == nil || IsNil(o.Aws) {
		var ret int32
		return ret
	}
	return *o.Aws
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetAwsOk() (*int32, bool) {
	if o == nil || IsNil(o.Aws) {
		return nil, false
	}
	return o.Aws, true
}

// HasAws returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasAws() bool {
	if o != nil && !IsNil(o.Aws) {
		return true
	}

	return false
}

// SetAws gets a reference to the given int32 and assigns it to the Aws field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetAws(v int32) {
	o.Aws = &v
}

// GetAzure returns the Azure field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetAzure() int32 {
	if o == nil || IsNil(o.Azure) {
		var ret int32
		return ret
	}
	return *o.Azure
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetAzureOk() (*int32, bool) {
	if o == nil || IsNil(o.Azure) {
		return nil, false
	}
	return o.Azure, true
}

// HasAzure returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasAzure() bool {
	if o != nil && !IsNil(o.Azure) {
		return true
	}

	return false
}

// SetAzure gets a reference to the given int32 and assigns it to the Azure field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetAzure(v int32) {
	o.Azure = &v
}

// GetCiscat returns the Ciscat field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetCiscat() int32 {
	if o == nil || IsNil(o.Ciscat) {
		var ret int32
		return ret
	}
	return *o.Ciscat
}

// GetCiscatOk returns a tuple with the Ciscat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetCiscatOk() (*int32, bool) {
	if o == nil || IsNil(o.Ciscat) {
		return nil, false
	}
	return o.Ciscat, true
}

// HasCiscat returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasCiscat() bool {
	if o != nil && !IsNil(o.Ciscat) {
		return true
	}

	return false
}

// SetCiscat gets a reference to the given int32 and assigns it to the Ciscat field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetCiscat(v int32) {
	o.Ciscat = &v
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetCommand() int32 {
	if o == nil || IsNil(o.Command) {
		var ret int32
		return ret
	}
	return *o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetCommandOk() (*int32, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given int32 and assigns it to the Command field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetCommand(v int32) {
	o.Command = &v
}

// GetDocker returns the Docker field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetDocker() int32 {
	if o == nil || IsNil(o.Docker) {
		var ret int32
		return ret
	}
	return *o.Docker
}

// GetDockerOk returns a tuple with the Docker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetDockerOk() (*int32, bool) {
	if o == nil || IsNil(o.Docker) {
		return nil, false
	}
	return o.Docker, true
}

// HasDocker returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasDocker() bool {
	if o != nil && !IsNil(o.Docker) {
		return true
	}

	return false
}

// SetDocker gets a reference to the given int32 and assigns it to the Docker field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetDocker(v int32) {
	o.Docker = &v
}

// GetGcp returns the Gcp field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetGcp() int32 {
	if o == nil || IsNil(o.Gcp) {
		var ret int32
		return ret
	}
	return *o.Gcp
}

// GetGcpOk returns a tuple with the Gcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetGcpOk() (*int32, bool) {
	if o == nil || IsNil(o.Gcp) {
		return nil, false
	}
	return o.Gcp, true
}

// HasGcp returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasGcp() bool {
	if o != nil && !IsNil(o.Gcp) {
		return true
	}

	return false
}

// SetGcp gets a reference to the given int32 and assigns it to the Gcp field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetGcp(v int32) {
	o.Gcp = &v
}

// GetGithub returns the Github field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetGithub() int32 {
	if o == nil || IsNil(o.Github) {
		var ret int32
		return ret
	}
	return *o.Github
}

// GetGithubOk returns a tuple with the Github field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetGithubOk() (*int32, bool) {
	if o == nil || IsNil(o.Github) {
		return nil, false
	}
	return o.Github, true
}

// HasGithub returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasGithub() bool {
	if o != nil && !IsNil(o.Github) {
		return true
	}

	return false
}

// SetGithub gets a reference to the given int32 and assigns it to the Github field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetGithub(v int32) {
	o.Github = &v
}

// GetLogcollectorBreakdown returns the LogcollectorBreakdown field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetLogcollectorBreakdown() WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownLogcollectorBreakdown {
	if o == nil || IsNil(o.LogcollectorBreakdown) {
		var ret WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownLogcollectorBreakdown
		return ret
	}
	return *o.LogcollectorBreakdown
}

// GetLogcollectorBreakdownOk returns a tuple with the LogcollectorBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetLogcollectorBreakdownOk() (*WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownLogcollectorBreakdown, bool) {
	if o == nil || IsNil(o.LogcollectorBreakdown) {
		return nil, false
	}
	return o.LogcollectorBreakdown, true
}

// HasLogcollectorBreakdown returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasLogcollectorBreakdown() bool {
	if o != nil && !IsNil(o.LogcollectorBreakdown) {
		return true
	}

	return false
}

// SetLogcollectorBreakdown gets a reference to the given WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownLogcollectorBreakdown and assigns it to the LogcollectorBreakdown field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetLogcollectorBreakdown(v WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdownLogcollectorBreakdown) {
	o.LogcollectorBreakdown = &v
}

// GetOffice365 returns the Office365 field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetOffice365() int32 {
	if o == nil || IsNil(o.Office365) {
		var ret int32
		return ret
	}
	return *o.Office365
}

// GetOffice365Ok returns a tuple with the Office365 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetOffice365Ok() (*int32, bool) {
	if o == nil || IsNil(o.Office365) {
		return nil, false
	}
	return o.Office365, true
}

// HasOffice365 returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasOffice365() bool {
	if o != nil && !IsNil(o.Office365) {
		return true
	}

	return false
}

// SetOffice365 gets a reference to the given int32 and assigns it to the Office365 field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetOffice365(v int32) {
	o.Office365 = &v
}

// GetMsGraph returns the MsGraph field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetMsGraph() int32 {
	if o == nil || IsNil(o.MsGraph) {
		var ret int32
		return ret
	}
	return *o.MsGraph
}

// GetMsGraphOk returns a tuple with the MsGraph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetMsGraphOk() (*int32, bool) {
	if o == nil || IsNil(o.MsGraph) {
		return nil, false
	}
	return o.MsGraph, true
}

// HasMsGraph returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasMsGraph() bool {
	if o != nil && !IsNil(o.MsGraph) {
		return true
	}

	return false
}

// SetMsGraph gets a reference to the given int32 and assigns it to the MsGraph field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetMsGraph(v int32) {
	o.MsGraph = &v
}

// GetOscap returns the Oscap field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetOscap() int32 {
	if o == nil || IsNil(o.Oscap) {
		var ret int32
		return ret
	}
	return *o.Oscap
}

// GetOscapOk returns a tuple with the Oscap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetOscapOk() (*int32, bool) {
	if o == nil || IsNil(o.Oscap) {
		return nil, false
	}
	return o.Oscap, true
}

// HasOscap returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasOscap() bool {
	if o != nil && !IsNil(o.Oscap) {
		return true
	}

	return false
}

// SetOscap gets a reference to the given int32 and assigns it to the Oscap field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetOscap(v int32) {
	o.Oscap = &v
}

// GetOsquery returns the Osquery field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetOsquery() int32 {
	if o == nil || IsNil(o.Osquery) {
		var ret int32
		return ret
	}
	return *o.Osquery
}

// GetOsqueryOk returns a tuple with the Osquery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetOsqueryOk() (*int32, bool) {
	if o == nil || IsNil(o.Osquery) {
		return nil, false
	}
	return o.Osquery, true
}

// HasOsquery returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasOsquery() bool {
	if o != nil && !IsNil(o.Osquery) {
		return true
	}

	return false
}

// SetOsquery gets a reference to the given int32 and assigns it to the Osquery field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetOsquery(v int32) {
	o.Osquery = &v
}

// GetRootcheck returns the Rootcheck field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetRootcheck() int32 {
	if o == nil || IsNil(o.Rootcheck) {
		var ret int32
		return ret
	}
	return *o.Rootcheck
}

// GetRootcheckOk returns a tuple with the Rootcheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetRootcheckOk() (*int32, bool) {
	if o == nil || IsNil(o.Rootcheck) {
		return nil, false
	}
	return o.Rootcheck, true
}

// HasRootcheck returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasRootcheck() bool {
	if o != nil && !IsNil(o.Rootcheck) {
		return true
	}

	return false
}

// SetRootcheck gets a reference to the given int32 and assigns it to the Rootcheck field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetRootcheck(v int32) {
	o.Rootcheck = &v
}

// GetSca returns the Sca field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetSca() int32 {
	if o == nil || IsNil(o.Sca) {
		var ret int32
		return ret
	}
	return *o.Sca
}

// GetScaOk returns a tuple with the Sca field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetScaOk() (*int32, bool) {
	if o == nil || IsNil(o.Sca) {
		return nil, false
	}
	return o.Sca, true
}

// HasSca returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasSca() bool {
	if o != nil && !IsNil(o.Sca) {
		return true
	}

	return false
}

// SetSca gets a reference to the given int32 and assigns it to the Sca field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetSca(v int32) {
	o.Sca = &v
}

// GetSyscheck returns the Syscheck field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetSyscheck() int32 {
	if o == nil || IsNil(o.Syscheck) {
		var ret int32
		return ret
	}
	return *o.Syscheck
}

// GetSyscheckOk returns a tuple with the Syscheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetSyscheckOk() (*int32, bool) {
	if o == nil || IsNil(o.Syscheck) {
		return nil, false
	}
	return o.Syscheck, true
}

// HasSyscheck returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasSyscheck() bool {
	if o != nil && !IsNil(o.Syscheck) {
		return true
	}

	return false
}

// SetSyscheck gets a reference to the given int32 and assigns it to the Syscheck field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetSyscheck(v int32) {
	o.Syscheck = &v
}

// GetSyscollector returns the Syscollector field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetSyscollector() int32 {
	if o == nil || IsNil(o.Syscollector) {
		var ret int32
		return ret
	}
	return *o.Syscollector
}

// GetSyscollectorOk returns a tuple with the Syscollector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetSyscollectorOk() (*int32, bool) {
	if o == nil || IsNil(o.Syscollector) {
		return nil, false
	}
	return o.Syscollector, true
}

// HasSyscollector returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasSyscollector() bool {
	if o != nil && !IsNil(o.Syscollector) {
		return true
	}

	return false
}

// SetSyscollector gets a reference to the given int32 and assigns it to the Syscollector field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetSyscollector(v int32) {
	o.Syscollector = &v
}

// GetUpgrade returns the Upgrade field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetUpgrade() int32 {
	if o == nil || IsNil(o.Upgrade) {
		var ret int32
		return ret
	}
	return *o.Upgrade
}

// GetUpgradeOk returns a tuple with the Upgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) GetUpgradeOk() (*int32, bool) {
	if o == nil || IsNil(o.Upgrade) {
		return nil, false
	}
	return o.Upgrade, true
}

// HasUpgrade returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) HasUpgrade() bool {
	if o != nil && !IsNil(o.Upgrade) {
		return true
	}

	return false
}

// SetUpgrade gets a reference to the given int32 and assigns it to the Upgrade field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) SetUpgrade(v int32) {
	o.Upgrade = &v
}

func (o WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aws) {
		toSerialize["aws"] = o.Aws
	}
	if !IsNil(o.Azure) {
		toSerialize["azure"] = o.Azure
	}
	if !IsNil(o.Ciscat) {
		toSerialize["ciscat"] = o.Ciscat
	}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Docker) {
		toSerialize["docker"] = o.Docker
	}
	if !IsNil(o.Gcp) {
		toSerialize["gcp"] = o.Gcp
	}
	if !IsNil(o.Github) {
		toSerialize["github"] = o.Github
	}
	if !IsNil(o.LogcollectorBreakdown) {
		toSerialize["logcollector_breakdown"] = o.LogcollectorBreakdown
	}
	if !IsNil(o.Office365) {
		toSerialize["office365"] = o.Office365
	}
	if !IsNil(o.MsGraph) {
		toSerialize["ms-graph"] = o.MsGraph
	}
	if !IsNil(o.Oscap) {
		toSerialize["oscap"] = o.Oscap
	}
	if !IsNil(o.Osquery) {
		toSerialize["osquery"] = o.Osquery
	}
	if !IsNil(o.Rootcheck) {
		toSerialize["rootcheck"] = o.Rootcheck
	}
	if !IsNil(o.Sca) {
		toSerialize["sca"] = o.Sca
	}
	if !IsNil(o.Syscheck) {
		toSerialize["syscheck"] = o.Syscheck
	}
	if !IsNil(o.Syscollector) {
		toSerialize["syscollector"] = o.Syscollector
	}
	if !IsNil(o.Upgrade) {
		toSerialize["upgrade"] = o.Upgrade
	}
	return toSerialize, nil
}

type NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown struct {
	value *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown
	isSet bool
}

func (v NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) Get() *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown {
	return v.value
}

func (v *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) Set(val *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown(val *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown {
	return &NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown{value: val, isSet: true}
}

func (v NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDroppedBreakdownModulesBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


