/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WazuhStatsInnerAlertsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WazuhStatsInnerAlertsInner{}

// WazuhStatsInnerAlertsInner struct for WazuhStatsInnerAlertsInner
type WazuhStatsInnerAlertsInner struct {
	// Rule ID that matched the event
	Sigid *int32 `json:"sigid,omitempty"`
	// Alert level
	Level *int32 `json:"level,omitempty"`
	// Number of times the alert was raised during the specified hour
	Times *int32 `json:"times,omitempty"`
}

// NewWazuhStatsInnerAlertsInner instantiates a new WazuhStatsInnerAlertsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWazuhStatsInnerAlertsInner() *WazuhStatsInnerAlertsInner {
	this := WazuhStatsInnerAlertsInner{}
	return &this
}

// NewWazuhStatsInnerAlertsInnerWithDefaults instantiates a new WazuhStatsInnerAlertsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWazuhStatsInnerAlertsInnerWithDefaults() *WazuhStatsInnerAlertsInner {
	this := WazuhStatsInnerAlertsInner{}
	return &this
}

// GetSigid returns the Sigid field value if set, zero value otherwise.
func (o *WazuhStatsInnerAlertsInner) GetSigid() int32 {
	if o == nil || IsNil(o.Sigid) {
		var ret int32
		return ret
	}
	return *o.Sigid
}

// GetSigidOk returns a tuple with the Sigid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhStatsInnerAlertsInner) GetSigidOk() (*int32, bool) {
	if o == nil || IsNil(o.Sigid) {
		return nil, false
	}
	return o.Sigid, true
}

// HasSigid returns a boolean if a field has been set.
func (o *WazuhStatsInnerAlertsInner) HasSigid() bool {
	if o != nil && !IsNil(o.Sigid) {
		return true
	}

	return false
}

// SetSigid gets a reference to the given int32 and assigns it to the Sigid field.
func (o *WazuhStatsInnerAlertsInner) SetSigid(v int32) {
	o.Sigid = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *WazuhStatsInnerAlertsInner) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhStatsInnerAlertsInner) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *WazuhStatsInnerAlertsInner) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *WazuhStatsInnerAlertsInner) SetLevel(v int32) {
	o.Level = &v
}

// GetTimes returns the Times field value if set, zero value otherwise.
func (o *WazuhStatsInnerAlertsInner) GetTimes() int32 {
	if o == nil || IsNil(o.Times) {
		var ret int32
		return ret
	}
	return *o.Times
}

// GetTimesOk returns a tuple with the Times field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhStatsInnerAlertsInner) GetTimesOk() (*int32, bool) {
	if o == nil || IsNil(o.Times) {
		return nil, false
	}
	return o.Times, true
}

// HasTimes returns a boolean if a field has been set.
func (o *WazuhStatsInnerAlertsInner) HasTimes() bool {
	if o != nil && !IsNil(o.Times) {
		return true
	}

	return false
}

// SetTimes gets a reference to the given int32 and assigns it to the Times field.
func (o *WazuhStatsInnerAlertsInner) SetTimes(v int32) {
	o.Times = &v
}

func (o WazuhStatsInnerAlertsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WazuhStatsInnerAlertsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sigid) {
		toSerialize["sigid"] = o.Sigid
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Times) {
		toSerialize["times"] = o.Times
	}
	return toSerialize, nil
}

type NullableWazuhStatsInnerAlertsInner struct {
	value *WazuhStatsInnerAlertsInner
	isSet bool
}

func (v NullableWazuhStatsInnerAlertsInner) Get() *WazuhStatsInnerAlertsInner {
	return v.value
}

func (v *NullableWazuhStatsInnerAlertsInner) Set(val *WazuhStatsInnerAlertsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWazuhStatsInnerAlertsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWazuhStatsInnerAlertsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWazuhStatsInnerAlertsInner(val *WazuhStatsInnerAlertsInner) *NullableWazuhStatsInnerAlertsInner {
	return &NullableWazuhStatsInnerAlertsInner{value: val, isSet: true}
}

func (v NullableWazuhStatsInnerAlertsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWazuhStatsInnerAlertsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


