/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OverviewAgents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverviewAgents{}

// OverviewAgents struct for OverviewAgents
type OverviewAgents struct {
	// Active nodes in the cluster
	Nodes []OverviewAgentsNodesInner `json:"nodes"`
	// Recount of the number of Wazuh agents group by Wazuh groups
	Groups []AgentGroup `json:"groups"`
	// Recount of the number of Wazuh agents group by OS
	AgentOs []OverviewAgentsAgentOsInner `json:"agent_os"`
	AgentStatus AgentsSummaryStatus `json:"agent_status"`
	// Recount of the number of Wazuh agents group by version
	AgentVersion []OverviewAgentsAgentVersionInner `json:"agent_version"`
	LastRegisteredAgent []Agent `json:"last_registered_agent"`
}

type _OverviewAgents OverviewAgents

// NewOverviewAgents instantiates a new OverviewAgents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverviewAgents(nodes []OverviewAgentsNodesInner, groups []AgentGroup, agentOs []OverviewAgentsAgentOsInner, agentStatus AgentsSummaryStatus, agentVersion []OverviewAgentsAgentVersionInner, lastRegisteredAgent []Agent) *OverviewAgents {
	this := OverviewAgents{}
	this.Nodes = nodes
	this.Groups = groups
	this.AgentOs = agentOs
	this.AgentStatus = agentStatus
	this.AgentVersion = agentVersion
	this.LastRegisteredAgent = lastRegisteredAgent
	return &this
}

// NewOverviewAgentsWithDefaults instantiates a new OverviewAgents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverviewAgentsWithDefaults() *OverviewAgents {
	this := OverviewAgents{}
	return &this
}

// GetNodes returns the Nodes field value
func (o *OverviewAgents) GetNodes() []OverviewAgentsNodesInner {
	if o == nil {
		var ret []OverviewAgentsNodesInner
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *OverviewAgents) GetNodesOk() ([]OverviewAgentsNodesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *OverviewAgents) SetNodes(v []OverviewAgentsNodesInner) {
	o.Nodes = v
}

// GetGroups returns the Groups field value
func (o *OverviewAgents) GetGroups() []AgentGroup {
	if o == nil {
		var ret []AgentGroup
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *OverviewAgents) GetGroupsOk() ([]AgentGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *OverviewAgents) SetGroups(v []AgentGroup) {
	o.Groups = v
}

// GetAgentOs returns the AgentOs field value
func (o *OverviewAgents) GetAgentOs() []OverviewAgentsAgentOsInner {
	if o == nil {
		var ret []OverviewAgentsAgentOsInner
		return ret
	}

	return o.AgentOs
}

// GetAgentOsOk returns a tuple with the AgentOs field value
// and a boolean to check if the value has been set.
func (o *OverviewAgents) GetAgentOsOk() ([]OverviewAgentsAgentOsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentOs, true
}

// SetAgentOs sets field value
func (o *OverviewAgents) SetAgentOs(v []OverviewAgentsAgentOsInner) {
	o.AgentOs = v
}

// GetAgentStatus returns the AgentStatus field value
func (o *OverviewAgents) GetAgentStatus() AgentsSummaryStatus {
	if o == nil {
		var ret AgentsSummaryStatus
		return ret
	}

	return o.AgentStatus
}

// GetAgentStatusOk returns a tuple with the AgentStatus field value
// and a boolean to check if the value has been set.
func (o *OverviewAgents) GetAgentStatusOk() (*AgentsSummaryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentStatus, true
}

// SetAgentStatus sets field value
func (o *OverviewAgents) SetAgentStatus(v AgentsSummaryStatus) {
	o.AgentStatus = v
}

// GetAgentVersion returns the AgentVersion field value
func (o *OverviewAgents) GetAgentVersion() []OverviewAgentsAgentVersionInner {
	if o == nil {
		var ret []OverviewAgentsAgentVersionInner
		return ret
	}

	return o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value
// and a boolean to check if the value has been set.
func (o *OverviewAgents) GetAgentVersionOk() ([]OverviewAgentsAgentVersionInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentVersion, true
}

// SetAgentVersion sets field value
func (o *OverviewAgents) SetAgentVersion(v []OverviewAgentsAgentVersionInner) {
	o.AgentVersion = v
}

// GetLastRegisteredAgent returns the LastRegisteredAgent field value
func (o *OverviewAgents) GetLastRegisteredAgent() []Agent {
	if o == nil {
		var ret []Agent
		return ret
	}

	return o.LastRegisteredAgent
}

// GetLastRegisteredAgentOk returns a tuple with the LastRegisteredAgent field value
// and a boolean to check if the value has been set.
func (o *OverviewAgents) GetLastRegisteredAgentOk() ([]Agent, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastRegisteredAgent, true
}

// SetLastRegisteredAgent sets field value
func (o *OverviewAgents) SetLastRegisteredAgent(v []Agent) {
	o.LastRegisteredAgent = v
}

func (o OverviewAgents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverviewAgents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodes"] = o.Nodes
	toSerialize["groups"] = o.Groups
	toSerialize["agent_os"] = o.AgentOs
	toSerialize["agent_status"] = o.AgentStatus
	toSerialize["agent_version"] = o.AgentVersion
	toSerialize["last_registered_agent"] = o.LastRegisteredAgent
	return toSerialize, nil
}

func (o *OverviewAgents) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nodes",
		"groups",
		"agent_os",
		"agent_status",
		"agent_version",
		"last_registered_agent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOverviewAgents := _OverviewAgents{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOverviewAgents)

	if err != nil {
		return err
	}

	*o = OverviewAgents(varOverviewAgents)

	return err
}

type NullableOverviewAgents struct {
	value *OverviewAgents
	isSet bool
}

func (v NullableOverviewAgents) Get() *OverviewAgents {
	return v.value
}

func (v *NullableOverviewAgents) Set(val *OverviewAgents) {
	v.value = val
	v.isSet = true
}

func (v NullableOverviewAgents) IsSet() bool {
	return v.isSet
}

func (v *NullableOverviewAgents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverviewAgents(val *OverviewAgents) *NullableOverviewAgents {
	return &NullableOverviewAgents{value: val, isSet: true}
}

func (v NullableOverviewAgents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverviewAgents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


