/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LogtestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogtestRequest{}

// LogtestRequest struct for LogtestRequest
type LogtestRequest struct {
	// Token for the logtest session
	Token *string `json:"token,omitempty"`
	// Allowed values: syslog, json, snort-full, squid, eventlog, eventchannel, audit, mysql_log, postgresql_log, nmapg, iis, command, full_command, djb-multilog, multi-line
	LogFormat string `json:"log_format"`
	// Path string
	Location string `json:"location"`
	// Event to look for
	Event string `json:"event"`
}

type _LogtestRequest LogtestRequest

// NewLogtestRequest instantiates a new LogtestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogtestRequest(logFormat string, location string, event string) *LogtestRequest {
	this := LogtestRequest{}
	this.LogFormat = logFormat
	this.Location = location
	this.Event = event
	return &this
}

// NewLogtestRequestWithDefaults instantiates a new LogtestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogtestRequestWithDefaults() *LogtestRequest {
	this := LogtestRequest{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *LogtestRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogtestRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *LogtestRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *LogtestRequest) SetToken(v string) {
	o.Token = &v
}

// GetLogFormat returns the LogFormat field value
func (o *LogtestRequest) GetLogFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LogFormat
}

// GetLogFormatOk returns a tuple with the LogFormat field value
// and a boolean to check if the value has been set.
func (o *LogtestRequest) GetLogFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogFormat, true
}

// SetLogFormat sets field value
func (o *LogtestRequest) SetLogFormat(v string) {
	o.LogFormat = v
}

// GetLocation returns the Location field value
func (o *LogtestRequest) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *LogtestRequest) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *LogtestRequest) SetLocation(v string) {
	o.Location = v
}

// GetEvent returns the Event field value
func (o *LogtestRequest) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *LogtestRequest) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *LogtestRequest) SetEvent(v string) {
	o.Event = v
}

func (o LogtestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogtestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	toSerialize["log_format"] = o.LogFormat
	toSerialize["location"] = o.Location
	toSerialize["event"] = o.Event
	return toSerialize, nil
}

func (o *LogtestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"log_format",
		"location",
		"event",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogtestRequest := _LogtestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLogtestRequest)

	if err != nil {
		return err
	}

	*o = LogtestRequest(varLogtestRequest)

	return err
}

type NullableLogtestRequest struct {
	value *LogtestRequest
	isSet bool
}

func (v NullableLogtestRequest) Get() *LogtestRequest {
	return v.value
}

func (v *NullableLogtestRequest) Set(val *LogtestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLogtestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLogtestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogtestRequest(val *LogtestRequest) *NullableLogtestRequest {
	return &NullableLogtestRequest{value: val, isSet: true}
}

func (v NullableLogtestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogtestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


