/*
Wazuh API REST

The Wazuh API is an open-source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tools like cURL or any script or program that can make web requests. The Wazuh WUI relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh WUI. Use the Wazuh API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.  # Authentication  Wazuh API endpoints require authentication to be used. Therefore, all calls must include a JSON Web Token. JWT is an open standard (RFC 7519) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. Perform a call with `basicAuth` to `POST /security/user/authenticate` and obtain a JWT token to run any endpoint.  JWT tokens have a default duration of 900 seconds. To change this value, you must perform a call with a valid JWT token to `PUT /security/config`. After this change, you will need to get a new JWT token as all previously issued tokens are revoked when any change is performed on security configuration.  Login with USER and PASSWORD:  `curl -u <USER>:<PASSWORD> -k -X POST \"https://<HOST_IP>:55000/security/user/authenticate\"` ```json {     \"data\": {         \"token\": \"<YOUR_JWT_TOKEN>\"     },     \"error\": 0 } ``` Use the token from the previous response to perform any endpoint request:  `curl -k -X <METHOD> \"https://<HOST_IP>:55000/<ENDPOINT>\" -H  \"Authorization: Bearer <YOUR_JWT_TOKEN>\"`  Change the token base duration:  `curl -k -X PUT \"https://<HOST_IP>:55000/security/config\" -H \"Authorization: Bearer <YOUR_JWT_TOKEN>\" -d '{\"auth_token_exp_timeout\": <NEW_EXPIRE_TIME_IN_SECONDS>}'`  <SecurityDefinitions /> 

API version: 4.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown{}

// WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown struct for WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown
type WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown struct {
	// Events coming from agentd
	Agent *int32 `json:"agent,omitempty"`
	// Events coming from agentlessd
	Agentless *int32 `json:"agentless,omitempty"`
	// Synchronization events
	Dbsync *int32 `json:"dbsync,omitempty"`
	IntegrationsBreakdown *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownIntegrationsBreakdown `json:"integrations_breakdown,omitempty"`
	ModulesBreakdown *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownModulesBreakdown `json:"modules_breakdown,omitempty"`
	// Events coming from monitord
	Monitor *int32 `json:"monitor,omitempty"`
	// Events coming from remoted
	Remote *int32 `json:"remote,omitempty"`
	// Events coming from syslog remoted
	Syslog *int32 `json:"syslog,omitempty"`
}

// NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown instantiates a new WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown() *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown {
	this := WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown{}
	return &this
}

// NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownWithDefaults instantiates a new WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownWithDefaults() *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown {
	this := WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown{}
	return &this
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetAgent() int32 {
	if o == nil || IsNil(o.Agent) {
		var ret int32
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetAgentOk() (*int32, bool) {
	if o == nil || IsNil(o.Agent) {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given int32 and assigns it to the Agent field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetAgent(v int32) {
	o.Agent = &v
}

// GetAgentless returns the Agentless field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetAgentless() int32 {
	if o == nil || IsNil(o.Agentless) {
		var ret int32
		return ret
	}
	return *o.Agentless
}

// GetAgentlessOk returns a tuple with the Agentless field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetAgentlessOk() (*int32, bool) {
	if o == nil || IsNil(o.Agentless) {
		return nil, false
	}
	return o.Agentless, true
}

// HasAgentless returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasAgentless() bool {
	if o != nil && !IsNil(o.Agentless) {
		return true
	}

	return false
}

// SetAgentless gets a reference to the given int32 and assigns it to the Agentless field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetAgentless(v int32) {
	o.Agentless = &v
}

// GetDbsync returns the Dbsync field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetDbsync() int32 {
	if o == nil || IsNil(o.Dbsync) {
		var ret int32
		return ret
	}
	return *o.Dbsync
}

// GetDbsyncOk returns a tuple with the Dbsync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetDbsyncOk() (*int32, bool) {
	if o == nil || IsNil(o.Dbsync) {
		return nil, false
	}
	return o.Dbsync, true
}

// HasDbsync returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasDbsync() bool {
	if o != nil && !IsNil(o.Dbsync) {
		return true
	}

	return false
}

// SetDbsync gets a reference to the given int32 and assigns it to the Dbsync field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetDbsync(v int32) {
	o.Dbsync = &v
}

// GetIntegrationsBreakdown returns the IntegrationsBreakdown field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetIntegrationsBreakdown() WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownIntegrationsBreakdown {
	if o == nil || IsNil(o.IntegrationsBreakdown) {
		var ret WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownIntegrationsBreakdown
		return ret
	}
	return *o.IntegrationsBreakdown
}

// GetIntegrationsBreakdownOk returns a tuple with the IntegrationsBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetIntegrationsBreakdownOk() (*WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownIntegrationsBreakdown, bool) {
	if o == nil || IsNil(o.IntegrationsBreakdown) {
		return nil, false
	}
	return o.IntegrationsBreakdown, true
}

// HasIntegrationsBreakdown returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasIntegrationsBreakdown() bool {
	if o != nil && !IsNil(o.IntegrationsBreakdown) {
		return true
	}

	return false
}

// SetIntegrationsBreakdown gets a reference to the given WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownIntegrationsBreakdown and assigns it to the IntegrationsBreakdown field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetIntegrationsBreakdown(v WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownIntegrationsBreakdown) {
	o.IntegrationsBreakdown = &v
}

// GetModulesBreakdown returns the ModulesBreakdown field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetModulesBreakdown() WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownModulesBreakdown {
	if o == nil || IsNil(o.ModulesBreakdown) {
		var ret WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownModulesBreakdown
		return ret
	}
	return *o.ModulesBreakdown
}

// GetModulesBreakdownOk returns a tuple with the ModulesBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetModulesBreakdownOk() (*WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownModulesBreakdown, bool) {
	if o == nil || IsNil(o.ModulesBreakdown) {
		return nil, false
	}
	return o.ModulesBreakdown, true
}

// HasModulesBreakdown returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasModulesBreakdown() bool {
	if o != nil && !IsNil(o.ModulesBreakdown) {
		return true
	}

	return false
}

// SetModulesBreakdown gets a reference to the given WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownModulesBreakdown and assigns it to the ModulesBreakdown field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetModulesBreakdown(v WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdownModulesBreakdown) {
	o.ModulesBreakdown = &v
}

// GetMonitor returns the Monitor field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetMonitor() int32 {
	if o == nil || IsNil(o.Monitor) {
		var ret int32
		return ret
	}
	return *o.Monitor
}

// GetMonitorOk returns a tuple with the Monitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetMonitorOk() (*int32, bool) {
	if o == nil || IsNil(o.Monitor) {
		return nil, false
	}
	return o.Monitor, true
}

// HasMonitor returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasMonitor() bool {
	if o != nil && !IsNil(o.Monitor) {
		return true
	}

	return false
}

// SetMonitor gets a reference to the given int32 and assigns it to the Monitor field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetMonitor(v int32) {
	o.Monitor = &v
}

// GetRemote returns the Remote field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetRemote() int32 {
	if o == nil || IsNil(o.Remote) {
		var ret int32
		return ret
	}
	return *o.Remote
}

// GetRemoteOk returns a tuple with the Remote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetRemoteOk() (*int32, bool) {
	if o == nil || IsNil(o.Remote) {
		return nil, false
	}
	return o.Remote, true
}

// HasRemote returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasRemote() bool {
	if o != nil && !IsNil(o.Remote) {
		return true
	}

	return false
}

// SetRemote gets a reference to the given int32 and assigns it to the Remote field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetRemote(v int32) {
	o.Remote = &v
}

// GetSyslog returns the Syslog field value if set, zero value otherwise.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetSyslog() int32 {
	if o == nil || IsNil(o.Syslog) {
		var ret int32
		return ret
	}
	return *o.Syslog
}

// GetSyslogOk returns a tuple with the Syslog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) GetSyslogOk() (*int32, bool) {
	if o == nil || IsNil(o.Syslog) {
		return nil, false
	}
	return o.Syslog, true
}

// HasSyslog returns a boolean if a field has been set.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) HasSyslog() bool {
	if o != nil && !IsNil(o.Syslog) {
		return true
	}

	return false
}

// SetSyslog gets a reference to the given int32 and assigns it to the Syslog field.
func (o *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) SetSyslog(v int32) {
	o.Syslog = &v
}

func (o WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Agent) {
		toSerialize["agent"] = o.Agent
	}
	if !IsNil(o.Agentless) {
		toSerialize["agentless"] = o.Agentless
	}
	if !IsNil(o.Dbsync) {
		toSerialize["dbsync"] = o.Dbsync
	}
	if !IsNil(o.IntegrationsBreakdown) {
		toSerialize["integrations_breakdown"] = o.IntegrationsBreakdown
	}
	if !IsNil(o.ModulesBreakdown) {
		toSerialize["modules_breakdown"] = o.ModulesBreakdown
	}
	if !IsNil(o.Monitor) {
		toSerialize["monitor"] = o.Monitor
	}
	if !IsNil(o.Remote) {
		toSerialize["remote"] = o.Remote
	}
	if !IsNil(o.Syslog) {
		toSerialize["syslog"] = o.Syslog
	}
	return toSerialize, nil
}

type NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown struct {
	value *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown
	isSet bool
}

func (v NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) Get() *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown {
	return v.value
}

func (v *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) Set(val *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown(val *WazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown {
	return &NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown{value: val, isSet: true}
}

func (v NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWazuhAnalysisdStatsItemMetricsEventsReceivedBreakdownDecodedBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


