# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  codegen:
    cmds:
      - oapi-codegen --config=oapi-codegen.yaml  wazuh-openapi-patched.yaml
